### ISSUE TITLE
Metric memory wrong when checking on Centos 7

### ISSUE THREAD

**Issue by hoalequang** [sensu-plugins/sensu-plugins-memory-checks#45] opened 2016-09-22 11:02 UTC
Hi,
When client run on Centos 7 (systemd), the script metrics-memory-percent.rb returns  wrong values 
- run free command : 
  
  > free -b
  >           total        used        free      shared  buff/cache   available
  > Mem:     3880316928   424787968   145653760    33890304  3309875200  3145891840
  > Swap:             0           0           0
- run script : 

> metrics-memory.rb
> foo.memory.total 3880316928 1474542059
> foo.memory.free 160362496 1474542059
> foo.memory.buffers 0 1474542059
> foo.memory.cached 387592192 1474542059
> foo.memory.swapTotal 0 1474542059
> foo.memory.swapFree 0 1474542059
> foo.memory.dirty 40960 1474542059
> foo.memory.swapUsed 0 1474542059
> foo.memory.used 3719954432 1474542059
> foo.memory.usedWOBuffersCaches 3332362240 1474542059
> foo.memory.freeWOBuffersCaches 547954688 1474542059

**Comment by eheydrick** [comment] 2016-10-05 06:36
The check grabs memory usage from /proc/meminfo. I haven't looked too close but I suspect free and meminfo differ due to cached/buffer usage.

**Comment by hoalequang** [comment] 2017-02-08 07:06
Yes, you are right. In centos7, the cached/buffer usage is not true in /proc/meminfo. could you please help me get the right metric?

**Comment by alexwbaule** [comment] 2017-03-30 15:35
Trust in /proc/meminfo , Not in free.

Why the checks use a sh using free and metrics use the /proc/meminfo ?  Make the checks use /proc/meminfo too ! 

The math is very simple:
FreeTotal = MemFree + Buffers + Cached
UsedTotal = MemTotal - FreeTotal
PercentUsed = (UsedTotal / MemTotal) * 100

i Will do a fork and a pull request with the checks in pure ruby, using /proc/meminfo. OK ?

you have doubts ?

open the "free" with strace.

strace free -b

and look the output:
open("/proc/meminfo", O_RDONLY)         = 3

**Comment by majormoses** [comment] 2017-05-07 17:26
@alexwbaule thats a great idea for anything using `free` but there are some checks that use `vmstat` which are cross platform compatible (other *nix) and refactoring that will break things for existing users who do not run linux such as BSD.

**Comment by jpoizat** [comment] 2017-07-10 14:24
Seems I got the kind of same issue on Ubuntu 16.04 LTS : 
```
me@server:/opt/sensu/embedded/bin$ ./metrics-memory.rb
server.memory.total 7305617408 1499696063
server.memory.free 183648256 1499696063
server.memory.buffers 45379584 1499696063
server.memory.cached 145203200 1499696063
server.memory.swapTotal 0 1499696063
server.memory.swapFree 0 1499696063
server.memory.dirty 1581056 1499696063
server.memory.swapUsed 0 1499696063
server.memory.used 7121969152 1499696063
server.memory.usedWOBuffersCaches 6931386368 1499696063
server.memory.freeWOBuffersCaches 374231040 1499696063
me@server:/opt/sensu/embedded/bin$ ./metrics-memory-percent.rb
server.memory_percent.free 2.5018529960226465 1499696087
server.memory_percent.buffers 0.6217208137708161 1499696087
server.memory_percent.cached 1.9913119436106117 1499696087
server.memory_percent.dirty 0.015530405394040585 1499696087
server.memory_percent.swapUsed 0.0 1499696087
server.memory_percent.usedWOBuffersCaches 94.88511424659593 1499696087
server.memory_percent.freeWOBuffersCaches 5.114885753404074 1499696087
me@server:/opt/sensu/embedded/bin$ cat /proc/meminfo
MemTotal:        7134392 kB
MemFree:          143252 kB
MemAvailable:    1910804 kB
Buffers:           43572 kB
Cached:            95416 kB
SwapCached:            0 kB
Active:          4818020 kB
Inactive:          37528 kB
Active(anon):    4719832 kB
Inactive(anon):      272 kB
Active(file):      98188 kB
Inactive(file):    37256 kB
Unevictable:        3656 kB
Mlocked:            3656 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               792 kB
Writeback:             0 kB
AnonPages:       4720224 kB
Mapped:            72868 kB
Shmem:              1124 kB
Slab:            1988720 kB
SReclaimable:    1927476 kB
SUnreclaim:        61244 kB
KernelStack:       18656 kB
PageTables:        16248 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     3567196 kB
Committed_AS:    7927416 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:   2463744 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      126912 kB
DirectMap2M:     7213056 kB
me@server:/opt/sensu/embedded/bin$
```
looking at it, it seems that the metrics a missing a digit... while the check looks ok :
me@server:/opt/sensu/embedded/bin$ ./check-memory.rb
MEM OK - free system memory: 1859 MB

not sure it's the same, but here checks looks more accurate than metrics...

**Comment by majormoses** [comment] 2017-07-10 15:57
I agree that there is much left to be desired on this front, I am all for making things better if you or someone else would submit a **safe** pr that does not lose compatibility for *nix I am all for it. I only rejected the PR because it included unnecessary breaking changes and lack of response on feedback. For anything using `free` we can switch over to `/proc/meminfo` but ones like vmstat use a different method to do cross platform support; there was no reason to change it to use `/proc/meminfo` as that defeated the purpose of it's existence.

**Comment by jpoizat** [comment] 2017-09-13 12:05
I did face the issue as well.
it seems that the issue is coming from the fact Ubuntu 16.04 is using a lot of SReclaimable memory... which is removed from free but not in the metrics... ( https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773 )
What about using MemAvailable when existing ? it is at least in Ubuntu 16.04 the one I'm using... and seems to be the best approach on available memory...

**Comment by majormoses** [comment] 2017-09-13 18:24
@jpoizat if you are using `check-ram.rb` that is indeed what I added here: https://github.com/sensu-plugins/sensu-plugins-memory-checks/pull/56 and the upstream functionality was merged here: https://github.com/threez/ruby-vmstat/commit/5c13458dfbb0a2297d4a358fd157fdd574ba76c3 

If you would like to add similar functionality to the other checks in a safe way I am :+1:

**Comment by jpoizat** [comment] 2017-09-15 13:26
Wouldn't it make more sense to create a new counter in case MemAvailable exist ?
so far, I came up with something like that, but I'm not sure this is the right way... :
```
  mem['available'] = line.split(/\s+/)[1].to_i * 1024 if line =~ /^MemAvailable/
...
    # if MemAvailable exist, use it to calculate "available memory"
    if mem.key?('available')
      mem['usedWOBuffersCaches'] = mem['total'] - mem['available']
      mem['freeWOBuffersCaches'] = mem['available']
    else
      mem['usedWOBuffersCaches'] = mem['used'] - (mem['buffers'] + mem['cached'])
      mem['freeWOBuffersCaches'] = mem['free'] + (mem['buffers'] + mem['cached'])
    end
```

**Comment by majormoses** [comment] 2017-09-15 16:43
seems reasonable from a quick glance.

**Comment by majormoses** [comment] 2017-09-23 17:25
If you are running new enough kernels with `MemAvailable` this is fixed and I do not see a good fix for older kernel versions.

**Closed as completed by majormoses** 2017-09-23 17:25 UTC
